services:
  front:
    build: ./front
    ports:
      - "3006:3006"
    volumes:
      - "./front:/usr/src/app/front"
  back:
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - "./back:/usr/src/app/back"