on: [push]

name: Build & Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - run: |
          npm install
          npm build
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: front-projet-octobre
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: front-projet-octobre/emmanueldessaint/nodejs:latest
          target: nodejs
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   strategy:
  #     matrix:
  #       browser: ['chrome', 'edge']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Cache node_modules
  #       id: cache-node_modules
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v4
  #       with:
  #         build: npm run build
  #         start: npm run start
  #         browser: ${{ matrix.browser }}
  #     - uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: cypress-videos
  #         path: cypress/videos
  #     - uses: actions/upload-artifact@v3
  #       if: failure()
  #       with:
  #         name: cypress-screenshots
  #         path: cypress/screenshots
